### PR TITLE
Fixed CGFloat check and Swizzling logic

### PR DESCRIPTION
**Pull request by cmezak**
Original implementation swizzled the addAnimation method every time the first easing function was added to an instance of CALayer, but this only needs to happen once for the whole class. 

Now, the swizzling only happens the first time an easing function is added to CALayer and the swizzle is never undone. If there's a good reason to undo the swizzling (performance, maybe?), then we should use a static counter variable that instances increment/decrement as easing functions are added and removed. Once the counter reaches 0, we can unswizzle.

Also changed the check for the type of the original animation's from value so it catches both floats and doubles as CGFloat.

### CODE REVIEW

**Comment by zrxq** [comment]
Why would you want to catch both doubles and floats as CGFloat?

Also I'm struggling to find a way to strip your original commit from the `xcuserdata` files, I probably should add that stuff to .gitignore in the future.

**Comment by cmezak** [comment]
Err, yeah, sorry about the xcuserdata stuff. Try [this](http://stackoverflow.com/questions/49478/git-ignore-file-for-xcode-projects) for the gitIgnore.

CGFloat, as you know, is either a double or a float. I ran into a case where CGFloat was a float, but the fromValue of my animation was a double. In this case, the fromValue was the result of calling [view.layer valueForKeyPath:@"transform.rotation"];. I don't know why the result there was not the same as CGFloat's type, but there you go. Is there any reason _not_ to check for both?

**Comment by zrxq** [comment]
Indeed, CGFloat can be either float or double, but that, to the best of my understanding, depends on a compile-time definition, so @encode(CGFloat) should work just fine (I'm not saying it does). 

How exactly did you trigger the animation that resulted in `transform.rotation` key path?

**Comment by cmezak** [comment]
I added the animation manually to the layer. Originally, I was just setting the view's transform property in a UIView animation, but the problem was that I only wanted the easing function applied to the rotation of the transform rather than the entire transform. So I set the easing function on the view for the "transform.rotation" key path. However, if I then just set the view's transform, the resulting animation will be on the "transform" key path. Long story short, to get the easing function working how I wanted, I had to create a CABasicAnimation myself. No big deal.

The weirdness comes in when I set the animation's fromValue to be the view's transform's current rotation value. That value's objCType returned "d" even though CGFloat was "f". I'm not sure why this is the case, but it seems reasonable to check for both "d" and "f".

**Comment by zrxq** [comment]
I just merged your fix for the swizzling issue. Thanks!

Regarding the float/double situation: The category was originally intended to work with `UIView`'s animatable properties only. While I see no reasons why it shouldn't work with `UILayer` properties as well, that would require adding support for a few more data types in addition to `float`/`double` – `CGAffineTransform` and `CGSize`, for example, are not yet supported as well. I should think about this more.

In your particular case you could use [CAKeyframeAnimation+AHEasing](https://github.com/warrenm/AHEasing/blob/master/AHEasing/CAKeyframeAnimation%2BAHEasing.h) category from AHEasing, `animationWithKeyPath:function:fromValue:toValue:` factory method to produce the required `CAAnimation`.

**Comment by zrxq** [comment]
On the other hand, it might be a good idea to add some aliases, like `transform.rotation` and `transform.scale`, that would make the easing function to only affect the relevant entries of the transformation matrix. I'm not very fond of messing with KVO, but it already happens when the category translates `alpha` into `opacity` or `frame` into `position`+`bounds`.

**Comment by cmezak** [comment]
Hmm, yeah that's a good call. I don't think it would solve the CGFloat check issue, though. That seems to result from the fact that [view valueForKeyPath:@"transform.rotation"] is returning a type that differs from CGFloat.

**Comment by zrxq** [comment]
I don't think it's possible to trigger an UIView animation (i.e. so called block-based animation) that would affect `transform.rotation`. The entire point of the category is to enable the use of easing functions without having to directly manipulate the backing `CALayer`. If you work on the layer level, it makes much more sense to feed the layer with a `CAKeyframeAnimation` directly, without all the swizzling voodoo.

**Comment by cmezak** [comment]
You're right!

**Comment by cmezak** [comment]
…Except that it _is_ possible to trigger a UIView animation that would affect transform.rotation. You can set the transform property of the view.

**Comment by zrxq** [comment]
Do you have a code sample?
—
Zoreslav Khimich

**Pull request closed without merging**
